# -*- coding: utf-8 -*-
"""Tran Thu Huong NGUYEN _reputation_game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3Jd7ou5HSLowMo8ro47vDIr5qpVQfg5
"""

import csv

# Step 1: Load scenarios from CSV
def load_scenarios(filename):
    scenarios = []
    with open(filename, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            scenario = {
                "id": int(row["ID"]),
                "question": row["Question"],
                "options": {
                    "A": {"text": row["OptionA"], "impact": int(row["ImpactA"])},
                    "B": {"text": row["OptionB"], "impact": int(row["ImpactB"])},
                    "C": {"text": row["OptionC"], "impact": int(row["ImpactC"])}
                }
            }
            scenarios.append(scenario)
    return scenarios

# Step 2: Ask for player name
def get_player_name():
    name = input("Enter your name: ").strip()
    while not name:
        name = input("Name cannot be empty. Please enter your name: ").strip()
    return name

# Step 3: Play the game
def play_game(scenarios):
    total_score = 0
    for scenario in scenarios:
        print(f"\nScenario {scenario['id']}: {scenario['question']}")
        for key, option in scenario['options'].items():
            print(f"{key}: {option['text']}")
        choice = input("Choose A, B, or C: ").strip().upper()
        while choice not in scenario['options']:
            choice = input("Invalid choice. Please choose A, B, or C: ").strip().upper()
        impact = scenario['options'][choice]['impact']
        total_score += impact
        print(f"Impact: {impact} | Total Score: {total_score}")
    return total_score

# Step 4: Convert score to percentage
def calculate_percentage(score, max_score, min_score):
    percentage = ((score - min_score) / (max_score - min_score)) * 200 - 100
    return round(percentage, 2)

# Step 5: Save result to results.csv
def save_result(name, percentage, filename="results.csv"):
    with open(filename, mode='a', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow([name, percentage])

# Step 6: Main function to run the game
def main():
    scenarios = load_scenarios("scenarios_batch.csv")
    name = get_player_name()
    score = play_game(scenarios)

    # Calculate min and max possible scores
    min_score = sum(min(opt['impact'] for opt in s['options'].values()) for s in scenarios)
    max_score = sum(max(opt['impact'] for opt in s['options'].values()) for s in scenarios)

    percentage = calculate_percentage(score, max_score, min_score)
    print(f"\n🎯 {name}, your final score is {score}, which is {percentage}%")
    save_result(name, percentage)
    print("Your result has been saved to results.csv.")

# Run the game
if __name__ == "__main__":
    main()